highlighter: rouge

permalink: /blog/:title/

baseurl: /RSSReader

title : RSS Reader
author :
  name : Rémy Gardette
  website: http://remyg.fr
  email : github@remyg.fr
  github : RemyG
  twitter : remygardette
